ipc = on

wallpaper{
    monitor = HDMI-A-1
    path = ~/Pictures/ScreenPictures/SafeBackground.jpg
    fit_mode = cover
}

wallpaper{
    monitor = eDP-1
    path = ~/Pictures/ScreenPictures/SafeBackground.jpg
    fit_mode = cover
}
